### ISSUE TITLE
Investigate GPEDIT steps

### ISSUE THREAD

**Issue by forderud** [forderud/IntelliMouseDriver#21]
The firefly sample documents the following Group Policy changes: https://github.com/microsoft/Windows-driver-samples/tree/main/hid/firefly#installation :
   1. In the Group Policy Object Editor navigation pane, open the Computer Configuration folder. Then open Administrative Templates, open System, open Device Installation, and then open Device Installation Restrictions.

   1. Enable *Prevent installation of devices not described by other policy settings*. This will prevent Windows from automatically installing the default mouse driver so that you can then install Firefly.

   1. Enable *Allow administrators to override device installation policy*. This will allow you to bypass the ""The installation of this device is forbidden by system policy" error that you may otherwise receive when you attempt to install Firefly.

   1. You may need to reboot.

**TASK**: Investigate if these settings still have any value.

**Comment by ManOnTheMountainTech** [comment]
For "Prevent installation of devices not described by other policy setting:" NOTE: This policy setting has been replaced by the "**Apply layered order of evaluation for Allow and Prevent device installation policies across all device match criteria**" policy setting to provide more granular control. It is recommended that you use the "Apply layered order of evaluation for Allow and Prevent device installation policies across all device match criteria" policy setting instead of this policy setting.

**Comment by ManOnTheMountainTech** [comment]
Actually "Allow administrators to override Device Installation Restriction policies"

**Comment by forderud** [comment]
Closing issue, since GPEDIT modifications does not seem to be required for driver loading after adding driver certificates to the `root` and `trustedpublisher` stores in #53.
